language: node_js
node_js: node
cache: yarn
before_install:
    - git config --global user.email $GITHUB_EMAIL
    - git config --global user.name $GITHUB_USERNAME
    - yarn global add hexo-cli
    - git clone $IMAGE_URI source/images
script:
    - hexo clean
    - hexo generate
after_success:
    - cd public
    - git init
    - git add .
    - git commit -m "Travis Deploy"
    - git push -f -q $GITHUB_URI master:gh-pages
