title: 'Re:Member'
# subtitle: 'Recovery'
description: null
author: zccz14
language: zh-CN
timezone: null
url: 'https://zccz14.com'
root: /
permalink: ':year/:month/:day/:post_title/'
permalink_defaults: null
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: code
i18n_dir: ':lang'
skip_render:
search:
  path: search.xml
  field: all
new_post_name: ':title.md'
default_layout: post
titlecase: false
external_link: true
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: null
default_category: uncategorized
category_map: null
tag_map: null
date_format: YYYY-MM-DD
time_format: 'HH:mm:ss'
per_page: 10
pagination_dir: page
theme: material
feed:
  type: atom
  path: atom.xml
  limit: 0
  hub:
  content: true
